parserOptions:
  ecmaVersion: 2017

plugins:
  - prettier

extends:
  - prettier

rules:
  constructor-super: 2
  default-case: 2
  eol-last: 2
  handle-callback-err: 2
  id-length: 2
  no-console: 0
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-lonely-if: 2
  no-magic-numbers: [2, {ignore: [-1, 0, 1]}]
  no-shadow: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-var: 2
  no-whitespace-before-property: 2
  object-curly-spacing: [2, never]
  object-shorthand: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prefer-spread: 2
  prefer-template: 2
  prettier/prettier: [2, {
      singleQuote: true,
      trailingComma: all,
      bracketSpacing: false,
      printWidth: 100
    }
  ]
  sort-keys: [2, asc, {caseSensitive: true, natural: true}]
  sort-vars: 2
  spaced-comment: [2, always, {exceptions: ['#', '/']}]
  strict: [2, global]
