project_identifier: wire-cs
base_path: .

files:
  -
    source: '/electron/locale/strings.js'
    translation: '/electron/locale/strings-%two_letters_code%.js'
    update_option: 'update_as_unapproved'
