name: Build

on:
  push:
    branches: [main, dev, staging]
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: build
        run: yarn build:linux

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: wrap/dist/Wire-*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: build
        run: echo "TODO"

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: build
        run: echo "TODO"
