name: E2E Tests

on:
  workflow_dispatch:
  schedule:
    # Execute workflow every night throughout the week
    - cron: '37 04 * * 1-5'

jobs:
  run_tests:
    name: Run E2E Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - uses: 1password/install-cli-action@8d006a0d0a4fd505af7f7ce589e7f768385ff5e4
      - name: Generate env file
        run: op inject -i e2e-tests/.env.tpl -o e2e-tests/.env
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build application
        run: yarn prestart

      - name: Run E2E tests
        run: yarn test:e2e
